# Site
repository: kennyta0204/kennyta0204.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kenny Tang
title: Aspiring Data Scientist
email: kennytang0204@gmail.com
website: https://kennyta0204.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  kennyta0204
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: Kenny Tang
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Kenny and I am an aspiring data scientist with an overflowing passion for the field. I recently graduated from the Univrsity of Michigan, Ann Arbor with a Master's degree in Applied Data Science. Prior to my graduate studies, I studied Economics and Accounting during my undergraduate years and worked as a Tax Accountant for two years before pursuing Data Science. 

  I have a strong interest in predictive modeling with project experiences in various machine learning techiniques/algorithms such as natural language processing, regression modeling, neural networks, and more. Outside of machine learning, I am confident with SQL and have  dabbled with making simple web applications. My primary programming language is Python and I have limited experiences with Matlab.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Used Cars Reccomender System
        link: <a href= "https://github.com/kennyta0204/Cars">kennyta0204/Cars<\a>
        # link_text: Project Website
        additional_links:
          - title:  Cars
            icon: fab fa-github
            url: https://github.com/kennyta0204/Cars
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Ever have a friend come to you for advice regarding what car they should get? You hear their criteria and try to think of all the possible vehicles that fit their description but you could never think of all on the spot. I have been in this situation many times and have come up with a solution!
        description: | # this will include new lines to allow paragraphs
          This is my most recent project that I started as a means of touching up my sql skills. Through the process, I became overly invested in the project and have since went beyond SQL. I took what was meant to be a simple postgres database into a fully fledged working web application with a search and recommender function. Though this project, I learned HTML and simple CSS to serve as the backbone of my app's front end interface. To sum up my work, I aggregated data from various sources, created a postgres SQL database, trained and implemented an unsupervised learning model that finds similar vehicles using a custom defined distance metric, and coded a web app.
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
